#
# FILE: Makefile
# PROJECT: A3
# PROGRAMMER: JESSICA SIM
# FIRST VERSION: 2021-01-25
# DESCRIPTION: This file is a Makefile to compile all the source codes. It also has ability to 
# clean bin and obj directory
#

#
# this makefile will compile and and all source
# found in the "DC" directory.  This represents a sample
# development directory structure and project
# 
# =======================================================
#                  DC Example
# =======================================================
# FINAL BINARY Target
all:
	cd ../DC/;make -f ./Makefile
	cd ../DR/;make -f ./Makefile
	cd ../DX/;make -f ./Makefile
clean:
	cd ../DC/;make clean -f ./Makefile
	cd ../DR/;make clean -f ./Makefile
	cd ../DX/;make clean -f ./Makefile
